tools/report4/reader/views.py
from flask import Blueprint, render_template, session, request, redirect
from models import *
from database import db_session
from helpers_http import *
from helpers_models import *
import settings
import queries as queries
import json
from forms import *

views = Blueprint('views', __name__)


@views.route("/")
def index():
    # tag = db_session.query(Tag).filter_by(highlight = True).first()
    # if tag:
    #     return redirect(url_for('views.highlights', tag_id=tag.id))
    return redirect(url_for('views.tutoriais'))


@views.route("/tutoriais")
def tutoriais():
    folder = Path(settings.app_dir / "static/tutorial_videos/geral")
    files_general = folder.iterdir()
    if settings.exec_mode != 'portable':
        folder = Path(settings.app_dir / "static/tutorial_videos/peritos")
        files_peritos = folder.iterdir()
    else:
        files_peritos = None
    return render_template(f"tutorial/home.html", files_general=files_general, files_peritos=files_peritos)


@views.route("/chat-list/<int:page>", methods=['GET', 'POST'])
def chat_list(page):
    form = ChatForm(request.form)
    query = make_filter(Chat)
    if form.validate_on_submit() or request.method == 'GET':
        query = queries.chat_list(query, form)
    pagination = get_page(query, settings.per_page['chat'], page=page)
    return render_template("chat_list.html", pagination=pagination, form=form)


@views.route("/tags")
def tags():
    tags = db_session.query(Tag).all()
    return render_template("tags.html", tags=tags)


@views.route("/tag-post", methods=["POST"])
def tag_post():
    id = request.form['id']
    if id:
        tag = db_session.query(Tag).get(id)
    else:
        tag = Tag()
    tag.name = request.form["name"]
    tag.color = request.form["color"]
    tag.description = request.form['description']
    tag.highlight = True if 'highlight' in request.form.keys() else False
    db_session.add(tag)
    db_session.commit()
    return redirect(url_for("views.tags"))


# @views.route("/files/<type_>/<int:page>")
# def files(page, type_=None):
#     form = FileForm(request.form)
#     form.type_ == type_
#     query = make_filter(File)
#     pagination = get_page(query, per_page=settings.per_page[type_], page=page)
#     return render_template('files-details.html', pagination=pagination, title="Arquivos", args={}, view='views.files_post', form=form)


@views.route("/files/<int:page>", methods=['GET', 'POST'])
def files(page):
    query = make_filter(File)
    form = FileForm(request.form)
    if request.method == 'POST' and form.validate():
        query = queries.files(query, form)
    per_page = settings.per_page[form.type_.data] if form.type_.data != 'all' else settings.per_page['file']
    pagination = get_page(query, per_page=per_page, page=page)
    try:
        template = 'files-table.html' if session['file_vizualization'] == 'table' else 'files-mini.html'
    except KeyError:
        session['file_vizualization'] = 'table'
        template = 'files-table.html'
    return render_template(template, pagination=pagination, args={}, view='views.files', form=form)


@views.route("/chat/<int:page>", methods=['GET', 'POST'])
def chat(page):
    form = MessageForm(request.form)
    query = make_filter(Message, db_session.query(Message).join(Chat))
    if request.method == 'POST' and form.validate():
        query = queries.messages(query, form)
        chat = db_session.query(Chat).get(form.chat_id.data) if form.chat_id.data else None
    else:
        chat_id = request.args.get('chat_id', type=int)
        if chat_id:
            chat = db_session.query(Chat).get(chat_id)
            query = query.filter(Message.chat_id == chat_id).order_by(Message.timestamp.asc())
            form.chat_id.data = chat_id
        else:
            chat = None
            db_session.query(Message).order_by(Message.timestamp.asc())

    pagination = get_page(query, per_page=settings.per_page['chat'], page=page)
    return render_template("chat.html", chat=chat, pagination=pagination, view='views.chat', args={}, form=form)


@views.route("/smss/<int:page>", methods=['GET', 'POST'])
def smss(page):
    form = SmsForm(request.form)
    query = make_filter(Sms)
    if request.method == 'POST' and form.validate():
        query = queries.smss(query, form)
    else:
        query = query.order_by(Sms.timestamp.asc())
    pagination = get_page(query, per_page=settings.per_page['sms'], page=page)
    return render_template("smss.html", pagination=pagination, view='views.smss', form=form)


@views.route("/contacts/<int:page>", methods=['GET', 'POST'])
def contacts(page):
    form = ContactForm(request.form)
    query = make_filter(Contact)
    if request.method == 'POST' and form.validate():
        query = queries.contacts(query, form)
    else:
        query = query.order_by(Contact.name.asc())
    pagination = get_page(query, per_page=settings.per_page['contact'], page=page)
    return render_template("contacts.html", pagination=pagination, view='views.contacts', form=form)


@views.route("/calls/<int:page>", methods=['GET', 'POST'])
def calls(page):
    form = CallForm(request.form)
    query = make_filter(Call)
    if request.method == 'POST' and form.validate():
        query = queries.calls(query, form)
    else:
        query = query.order_by(Call.timestamp.asc())
    pagination = get_page(query, per_page=settings.per_page['call'], page=page)
    return render_template("calls.html", pagination=pagination, view='views.calls', form=form)


@views.route("/highlights/<int:tag_id>")
def highlights(tag_id):
    tag = db_session.query(Tag).get(tag_id)
    smss = db_session.query(Sms).filter(Sms.tags.any(Tag.id == tag.id)).order_by(Sms.timestamp.asc()).all()
    messages = db_session.query(Message).join(Chat).filter(Message.tags.any(Tag.id == tag.id)).order_by(Chat.id.asc(),
                                                                                            Message.timestamp.asc()).all()
    files = db_session.query(File).filter(File.tags.any(Tag.id == tag.id)).order_by(File.type_.asc()).all()
    return render_template('highlights.html', tag=tag, smss=smss, messages=messages, files=files)


@views.route("/filters")
def filters():
    filters = get_user_filters()
    tags = db_session.query(Tag).all()
    devices = db_session.query(Device).order_by(Device.folder.asc()).all()
    devices_ = [{'id': dev.id, 'folder': dev.folder, 'checked': dev.id not in filters['devices']} for dev in devices]
    tags_ = [{'id': tag.id, 'name': tag.name, 'checked': tag.id in filters['tags']} for tag in tags]
    data = {'devices': devices_, 'tags': tags_}
    return render_template("filters2.html", data=data)

@views.route("/filters", methods=['POST'])
def filters_post():
    payload = get_json_payload(request)
    set_user_filters(payload)
    return redirect(url_for('views.filters'))

tools/report4/reader/templates/backup.html
{% extends 'files.html' %}
{% block files %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                <div class="dropdown">
                    <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">Marcar
                        <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#" onclick="checkAll('File')">Marcar todos nesta página</a></li>
                        <li><a href="#" onclick="checkAllComplete('File')">Marcar todos filtrados</a></li>
                        <li><a href="#" onclick="uncheckAll('File')">Desmarcar todos nesta página</a></li>
                        <li><a href="#" onclick="uncheckAllComplete('File')">Desmarcar todos filtrados</a>
                        </li>
                    </ul>
                </div>
            </th>
            <th>
                <div class="dropdown">
                    <button class="btn btn-default btn-sm dropdown-toggle" type="button"
                        data-toggle="dropdown">Etiquetas
                        <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#" onclick="addManyTags('File')">Adicionar em todos nesta página</a>
                        </li>
                        <li><a href="#" onclick="addManyTagsComplete('File')">Adicionar em todos
                                filtrados</a></li>
                        <li><a href="#" onclick="removeManyTags('File')">Remover de todos nesta página</a>
                        </li>
                        <li><a href="#" onclick="removeManyTagsComplete('File')">Remover de todos
                                filtrados</a></li>
                    </ul>
                </div>
            </th>
            <th></th>
            <th>Vizualização</th>
            <th>
                <a href="#" onclick="orderBy('size', '{{form.order.data}}')">
                    Tamanho
                    {{ macros.ordered('size', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('filename', '{{form.order.data}}')">
                    Nome
                    {{ macros.ordered('filename', form) }}
                </a>

            </th>
            <th>
                <a href="#" onclick="orderBy('original_path', '{{form.order.data}}')">
                    Caminho original
                    {{ macros.ordered('original_path', form) }}
                </a>

            </th>
            <th>
                <a href="#" onclick="orderBy('creation_time', '{{form.order.data}}')">
                    Data de criação
                    {{ macros.ordered('creation_time', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('modify_time', '{{form.order.data}}')">
                    Data de modificação
                    {{ macros.ordered('modify_time', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('access_time', '{{form.order.data}}')">
                    Data de acesso
                    {{ macros.ordered('access_time', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('type_', '{{form.order.data}}')">
                    Tipo
                    {{ macros.ordered('type_', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('deleted_state', '{{form.order.data}}')">
                    Deletado
                    {{ macros.ordered('deleted_state', form) }}
                </a>
            </th>

        </tr>
    </thead>
    <tbody>

        {% for item in pagination['items'] %}
        <tr class="rm-item" item_id="{{ item.id }}">
            <td>
                {{ loop.index + pagination.first }}
                <input class="rm-check" type="checkbox" value="" {% if item.checked %}checked{% endif %}
                    rm_item_id="{{ item.id }}" rm_class="File">
            </td>
            <td class="rm-tags-container" id="tagsContainer{{ item.id }}">
                <span class="glyphicon glyphicon-tag rm-tag-add" style="color: {{ current_tag.color }};"
                    onclick="toggleOneTag('File', {{ item.id }})"></span>
                {% for tag in item.tags %}
                <span class="glyphicon glyphicon-tag rm-tag-id-{{ tag.id }}" style="color: {{ tag.color }};"></span>
                {% endfor %}
            </td>
            <td>
                {{ macros.action_button_file(item) }}
            </td>
            <td>
                {{ file(item, action_button=False) }}
            </td>
            <td>{{ item.size|filesize }}</td>
            <td>{{ item.filename|filename_max }}</td>
            <td>{{ item.original_path }}</td>
            <td>{{ item.creation_time|strftime_complete }}</td>
            <td>{{ item.modify_time|strftime_complete }}</td>
            <td>{{ item.access_time|strftime_complete }}</td>
            <td>{{ item.type_}}</td>
            <td>{{ item.deletado}}</td>
        </tr>
        {% endfor %}

    </tbody>
</table>

{% endblock %}

tools/report4/reader/templates/base-clean.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Analisador de dados</title>

    <link rel="stylesheet" href="{{url_for('static', filename='fontawesome-free-5.10.2-web/css/all.css')}}">

    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap-3.3.7/css/bootstrap.min.css')}}">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">

  
    <!-- jQuery -->
    <script src="{{ url_for('static', filename='jquery-3.4.1.min.js') }}" type="text/javascript"></script>

    <!-- Bootbox -->
    <script src="{{ url_for('static', filename='bootbox-4.4.0.min.js') }}" type="text/javascript"></script>

    <!-- Preloader -->
    <script type="text/javascript"
        src="{{ url_for('static', filename='preloader/jquery.preloaders.min.js') }}"></script>

    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap-3.3.7/js/bootstrap.min.js') }}"
        type="text/javascript"></script>

    <link href="{{ url_for('static', filename='bootstrap-colorpicker-2.5.2/css/bootstrap-colorpicker.min.css') }}"
        rel="stylesheet">
    <script
        src="{{ url_for('static', filename='bootstrap-colorpicker-2.5.2/js/bootstrap-colorpicker.min.js') }}"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

</head>

<body>
  {% block content %}
  {% endblock %}
</body>

</html>

tools/report4/reader/templates/calls.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "macros.html" as macros %}
{% block title %}
<h3>Registros de chamadas <span class="badge">{{ pagination['n_items'] }}</span></h3>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <ul class="nav nav-tabs">
                <li {% if not form.errors %}class="active" {% endif %}><a data-toggle="tab" href="#tabData">Registros de
                        chamadas</a></li>
                <li {% if form.errors %}class="active" {% endif %}><a data-toggle="tab" href="#tabFilter"> <span
                            class="glyphicon glyphicon-search"></span> Pesquisar</a>
                </li>
            </ul>
            <div class="tab-content">
                <div id="tabData" class="tab-pane fade{% if not form.errors %}in active{% endif %}">
                    <div class="rm-pagination-fixed">
                        {{ macros.pagination_links(pagination, view='views.calls', args={} ) }}
                    </div>

                    <table class="table table-striped table-drop">

                        <thead>
                            <tr>
                                <th>
                                    <div class="dropdown">
                                        <button class="btn btn-default btn-sm dropdown-toggle" type="button"
                                            data-toggle="dropdown">Marcar
                                            <span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><a href="#" onclick="checkAll('Call')">Marcar todos nesta página</a>
                                            </li>
                                            <li><a href="#" onclick="checkAllComplete('Call')">Marcar todos
                                                    filtrados</a>
                                            </li>
                                            <li><a href="#" onclick="uncheckAll('Call')">Desmarcar todos nesta
                                                    página</a>
                                            </li>
                                            <li><a href="#" onclick="uncheckAllComplete('Call')">Desmarcar todos
                                                    filtrados</a></li>
                                        </ul>
                                    </div>
                                </th>
                                <th>
                                    <div class="dropdown">
                                        <button class="btn btn-default btn-sm dropdown-toggle" type="button"
                                            data-toggle="dropdown">Etiquetas
                                            <span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><a href="#" onclick="addManyTags('Call')">Adicionar em todos nesta
                                                    página</a></li>
                                            <li><a href="#" onclick="addManyTagsComplete('Call')">Adicionar em todos
                                                    filtrados</a></li>
                                            <li><a href="#" onclick="removeManyTags('Call')">Remover de todos nesta
                                                    página</a></li>
                                            <li><a href="#" onclick="removeManyTagsComplete('Call')">Remover de todos
                                                    filtrados</a></li>
                                        </ul>
                                    </div>
                                </th>

                                <th>
                                    Partes
                                </th>
                                <th>
                                    <a href="#" onclick="orderBy('timestamp', '{{form.order.data}}')">
                                        Data/Hora
                                        {{ macros.ordered('timestamp', form) }}
                                    </a>
                                </th>
                                <th>
                                    <a href="#" onclick="orderBy('duration', '{{form.order.data}}')">
                                        Duração
                                        {{ macros.ordered('duration', form) }}
                                    </a>
                                </th>

                                <th>
                                    <a href="#" onclick="orderBy('deleted_state', '{{form.order.data}}')">
                                        Deletado
                                        {{ macros.ordered('deleted_state', form) }}
                                    </a>
                                </th>
                                <th>
                                    Objeto
                                </th>

                            </tr>
                        </thead>
                        <tbody>

                            {% for item in pagination['items'] %}
                            <tr class="rm-item" item_id="{{ item.id }}">
                                <td>
                                    {{ loop.index + pagination.first }}
                                    <input class="rm-check" type="checkbox" value=""
                                        {% if item.checked %}checked{% endif %} rm_item_id="{{ item.id }}"
                                        rm_class="Call">
                                </td>
                                <td class="rm-tags-container" id="tagsContainer{{ item.id }}">
                                    {{ macros.toggle_tag_icon('Call', item) }}
                                    {% for tag in item.tags %}
                                    <span class="glyphicon glyphicon-tag rm-tag-id-{{ tag.id }}"
                                        style="color: {{ tag.color }};"></span>
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for part in item.parties %}
                                    <p>
                                        <strong>{{ part.role }}:
                                        </strong>{{ part.identifier }}{% if part.name %}{{ ' ' + part.name }}{% endif %}
                                    </p>

                                    {% endfor %}
                                </td>
                                <td>{{ item.timestamp|strftime_complete }}</td>

                                <td>{{ item.duration if item.duration}}</td>

                                <td>{{ item.deleted_state }}</td>
                                <td>{{ item.read_source.device.folder }}</td>

                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                </div>
                <div id="tabFilter" class="tab-pane fade  {% if form.errors %}in active{% endif %}">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                {{ wtf.quick_form(form, id='frmFilter', action=request.url) }}

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


{% endblock %}

tools/report4/reader/templates/erro.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="padding-top: 100px;">
    <div class="row">
        <div class="col-md-12">
            <h3>Houve um erro</h3>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert {{ category }} alert-dismissable">

                <strong>Mensagem!</strong> {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </div>

</div>
{% endblock %}

tools/report4/reader/templates/files-table.html
{% extends 'files.html' %}
{% block files %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                <div class="dropdown">
                    <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">Marcar
                        <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#" onclick="checkAll('File')">Marcar todos nesta página</a></li>
                        <li><a href="#" onclick="checkAllComplete('File')">Marcar todos filtrados</a></li>
                        <li><a href="#" onclick="uncheckAll('File')">Desmarcar todos nesta página</a></li>
                        <li><a href="#" onclick="uncheckAllComplete('File')">Desmarcar todos filtrados</a>
                        </li>
                    </ul>
                </div>
            </th>
            <th>
                <div class="dropdown">
                    <button class="btn btn-default btn-sm dropdown-toggle" type="button"
                        data-toggle="dropdown">Etiquetas
                        <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#" onclick="addManyTags('File')">Adicionar em todos nesta página</a>
                        </li>
                        <li><a href="#" onclick="addManyTagsComplete('File')">Adicionar em todos
                                filtrados</a></li>
                        <li><a href="#" onclick="removeManyTags('File')">Remover de todos nesta página</a>
                        </li>
                        <li><a href="#" onclick="removeManyTagsComplete('File')">Remover de todos
                                filtrados</a></li>
                    </ul>
                </div>
            </th>
            <th></th>
            <th>Vizualização</th>
            <th>
                <a href="#" onclick="orderBy('size', '{{form.order.data}}')">
                    Tamanho
                    {{ macros.ordered('size', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('filename', '{{form.order.data}}')">
                    Nome
                    {{ macros.ordered('filename', form) }}
                </a>

            </th>
            <th>
                <a href="#" onclick="orderBy('original_path', '{{form.order.data}}')">
                    Caminho original
                    {{ macros.ordered('original_path', form) }}
                </a>

            </th>
            <th>
                <a href="#" onclick="orderBy('creation_time', '{{form.order.data}}')">
                    Data de criação
                    {{ macros.ordered('creation_time', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('modify_time', '{{form.order.data}}')">
                    Data de modificação
                    {{ macros.ordered('modify_time', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('access_time', '{{form.order.data}}')">
                    Data de acesso
                    {{ macros.ordered('access_time', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('type_', '{{form.order.data}}')">
                    Tipo
                    {{ macros.ordered('type_', form) }}
                </a>
            </th>
            <th>
                <a href="#" onclick="orderBy('deleted_state', '{{form.order.data}}')">
                    Deletado
                    {{ macros.ordered('deleted_state', form) }}
                </a>
            </th>

        </tr>
    </thead>
    <tbody>

        {% for item in pagination['items'] %}
        <tr class="rm-item" item_id="{{ item.id }}">
            <td>
                {{ loop.index + pagination.first }}
                <input class="rm-check" type="checkbox" value="" {% if item.checked %}checked{% endif %}
                    rm_item_id="{{ item.id }}" rm_class="File">
            </td>
            <td class="rm-tags-container" id="tagsContainer{{ item.id }}">

                {{ macros.toggle_tag_icon('File', item) }}
                {% for tag in item.tags %}
                <span class="glyphicon glyphicon-tag rm-tag-id-{{ tag.id }}" style="color: {{ tag.color }};"></span>
                {% endfor %}
            </td>
            <td>
                {{ macros.action_button_file(item) }}
            </td>
            <td>
                {{ macros.file(item, action_button=False) }}
            </td>
            <td>{{ item.size|filesize }}</td>
            <td>{{ item.filename }}</td>
            <td>{{ item.original_path }}</td>
            <td>{{ item.creation_time|strftime_complete }}</td>
            <td>{{ item.modify_time|strftime_complete }}</td>
            <td>{{ item.access_time|strftime_complete }}</td>
            <td>{{ item.type_}}</td>
            <td>{{ item.deleted_state}}</td>
        </tr>
        {% endfor %}

    </tbody>
</table>

{% endblock %}

tools/report4/reader/templates/filters2.html
{% extends 'base.html' %}
{% block content %}
    <div class="container" id="app">
        <div class="row">
            <div class="col">
                <table class="table table-bordered">
                    <tr>
                        <th>Objetos</th>
                        <th>Marcados como</th>
                    </tr>
                    <tr>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary btn-xs" @click="checkAllDevices">Marcar
                                    todos
                                </button>
                                <button type="button" class="btn btn-primary btn-xs" @click="uncheckAllDevices">
                                    Desmarcar todos
                                </button>
                            </div>
                            <input type="text" class="form-control" v-model="show_filter"
                                   placeholder="Digite algo para filtrar">


                        </td>
                        <td>Deixe todos vazios caso não deseje filtrar por etiqueta.
                        </td>
                    </tr>
                    <tr>
                        <td>

                            <div class="checkbox" v-for="(device, index) in devices_filtered">
                                 @{index + 1}
                                <label><input v-model="device.checked" type="checkbox"/>@{device.folder}</label>
                            </div>
                        </td>
                        <td>

                            <div class="checkbox" v-for="(tag, index) in tags">
                                @{index + 1}
                                <label><input type="checkbox" v-model="tag.checked"/>@{tag.name}</label>
                            </div>
                        </td>
                    </tr>
                </table>

            </div>
        </div>


        <div class="row">
            <div class="col-md-12 text-center">
                <button class="btn btn-primary" @click="submit">Gravar</button>
            </div>
        </div>
    </div>
    <script>
        var app = new Vue({
            el: '#app',
            delimiters: ['@{', '}'],
            data: {
                devices: {{ data.devices|tojson }},
                tags: {{ data.tags|tojson }},
                show_filter: ""
            },
            methods: {
                submit: function () {
                    self = this;
                    var filters = {
                        devices: [],
                        tags: []
                    }
                    for (var i = 0; i < self.devices.length; i++) {
                        if (!self.devices[i].checked) {
                            filters.devices.push(self.devices[i].id);
                        }
                    }
                    for (var i = 0; i < self.tags.length; i++) {
                        if (self.tags[i].checked) {
                            filters.tags.push(self.tags[i].id);
                        }
                    }
                    postJson("{{ url_for('views.filters_post') }}", filters);


                },
                checkAllDevices: function () {

                    this.devices_filtered.forEach(function (device) {
                        device.checked = true;
                    });

                },
                uncheckAllDevices: function () {
                    this.devices_filtered.forEach(function (device) {
                        device.checked = false;
                    });
                }
            },
            computed: {

                devices_filtered: function () {
                    self = this;
                    return this.devices.filter(function (device) {
                        return device.folder.includes(self.show_filter);
                    });
                }
            }
        })
    </script>
{% endblock %}